# Once you add your API key below, make sure to not share it with anyone! The API key should remain private.
# Get api key from --> https://platform.openai.com/account/api-keys
OPENAI_API_KEY="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"